# Once you add your API key below, make sure to not share it with anyone! The API key should remain private.
# Get api key from --> https://platform.openai.com/account/api-keys
OPENAI_API_KEY="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"